project:
  type: website

website:
  title: "Praachi Ajmera's Portfolio"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/PraachiAjmera9
format:
  html:
    theme: paper
    css: styles.css

